export interface FinalType {
    order? : number, 
    name? : string,
    alias? : string, 
    group_alias? : string , 
    tcp_port? : number, 
    udp_port? : number, 
    wi_port? : number, 
    wi_password? : string,
    max_connections?:number, 
    max_files? : number,
    downstream_limit?:number, 
    user_cache_reloading_interval? : number, 
    is_nat? : number, 
    proxify_ipv6? : number, 
    hidden? : number, 
    is_proxy? : number,
    threads?:number,
    password?:string, 
    zabbix_hostid? : string, 
    datacenter_id? : number, 
    logging? : number, 
    server_id? : number 
}